name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
  
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      
      
      # Login to DockerHub using docker credentials that keeps in GitHub Secrets
      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Use spesific tags for docker images
      -
        name: Docker meta tag
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: olesyudin/password-generator # Define repository to push
          tags: |
            type=raw,pattern=\d+,value=action-{{date 'DD.MM.YYYY'}}-{{branch}}-{{sha}}-{{tag}}

      # Docker build and push image to DockerHub
      -
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          # tags: ${{ secrets.DOCKER_USERNAME }}/password-generator:latest
          tags: ${{ steps.meta.outputs.tags }}