name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

docker-build:
  build:
    runs-on: alpine-3.15

    steps:
      # - uses: actions/checkout@v2
      # - name: Build Docker image
      #   run: |
      #     docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      #     docker tag  my-image-name:$(date +%s) olesyudin/password-generator:$(date +%s)

      # Login to DockerHub using docker credentials
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # Build Docker image and push it to DockerHub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/password-generator:github-$(date +%s)
