name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Login to DockerHub using docker credentials
      - uses: docker/login-action@v1
      - name: Docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v1

      # Build Docker image and push it to DockerHub
      - uses: docker/build-push-action@v2
      - name: Build and push Docker image
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/password-generator:github-$(date +%s)
